export { default as LoginForm } from "./sections/Login";
export { default as Input } from "./Input";
export { default as Particles } from "./Particles";
export { default as RegisterForm } from "./sections/Register";
export { default as DashboardPage } from "./sections/DashboardPage";
export { default as Header } from "./Header";
export { default as MainContainer } from "./MainContainer";
export { default as Aside } from "./Aside";
export { List } from "./List";
export { Layout } from "./Layout";
export { DiseasesComponent } from "./sections/DiseasesComponent";
export { PatientsComponent } from "./sections/PatientsComponent";
export { HistoryComponent } from "./sections/HistoryComponent";
